name: Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - run: |
            mkdir dist
            cp -r ./*.html dist/

      - name: Publish app
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: oystermercury-pypi-index-oversea
          directory: ./dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
